project:
  type: book
  output-dir: docs
  
book:
  title: SVM and Decision Tree
  author: Wendi Chu
  chapters:
    - index.ipynb
    - part: models
      chapters:
        - ./SVM_text_data.ipynb
        - ./DT_record_data.ipynb
format:
  html:
    theme: united
